// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHEunADFIViyYRy8CnnfLhAv5EA6king',
    appId: '1:660831772298:web:318317afdf5618e3841773',
    messagingSenderId: '660831772298',
    projectId: 'sleepapneacs',
    authDomain: 'sleepapneacs.firebaseapp.com',
    storageBucket: 'sleepapneacs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QeASOZhL8wK1STZBs0aD1cpcGF1oa8o',
    appId: '1:660831772298:android:462dbe168865f9de841773',
    messagingSenderId: '660831772298',
    projectId: 'sleepapneacs',
    storageBucket: 'sleepapneacs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7E0uxKxHr4mx3rlxJSFXwsNwhpjQ_TYk',
    appId: '1:660831772298:ios:0691c6ebfb34cbd0841773',
    messagingSenderId: '660831772298',
    projectId: 'sleepapneacs',
    storageBucket: 'sleepapneacs.appspot.com',
    iosClientId: '660831772298-0lbbu4hf35bm6nqqq9jnmvur8ue64c0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.apneatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7E0uxKxHr4mx3rlxJSFXwsNwhpjQ_TYk',
    appId: '1:660831772298:ios:0691c6ebfb34cbd0841773',
    messagingSenderId: '660831772298',
    projectId: 'sleepapneacs',
    storageBucket: 'sleepapneacs.appspot.com',
    iosClientId: '660831772298-0lbbu4hf35bm6nqqq9jnmvur8ue64c0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.apneatest',
  );
}
